audit_header: false
title: Greenville Real Estate Video Blog with Dan Hamilton
description: Our mission at Hamilton & Co. is to be your best resource for Greenville real estate advice. Whether you are a buyer, seller, or investor, our team of professionals can answer any questions you might have about real estate. If you are looking to buy or sell a home, you can get all the information and the latest updates, tips, and tricks from The Hamilton & Co., your professional Greenville Real Estate Agents.
show_custom_links: false
custom_links:
  - title:
    url:
show_custom_links_new_tab: false
custom_links_new_tab:
  - title:
    url:

client:
  name: Dan Hamilton
  title:
  license_number:
  about_markdown: |
    Dan Hamilton is a founding partner and the Operating Principal of Keller Williams Realty Greenville, one of the largest and fastest growing real estate brokerages in the Upstate. He is also the founder and Team Leader of Hamilton and Co. of Keller Williams Realty. A long time member of the Greenville community, Dan is passionate about serving and improving our community as has done so in of capacities, including as a member of the South Carolina House of Representatives for District 20 and as Vice Chairman of the Greenville County Redevelopment Authority.

    Dan and his team sell over 10 times as much real estate as the typical agent because of the systems they have in place to put the client first and aggressively market their listings using the latest technology available. It's simple, Dan's your man if you want the best in real estate.
  brand: Hamilton & Co.
  brokerage: Keller Williams
  market: Greenville
  address: 403 Woods Lake Road, Suite 100<br>Greenville, SC 29607
  phone: 864-527-7685
  phone_type:
  phone2:
  phone2_type:
  email: info@mygreenvillehome.com
  url: https://mygreenvillehome.com

CTAs:
  first_CTA_text: Home Valuation
  first_CTA_URL: http://www.mygreenvillehome.com/sell/
  second_CTA_text: Home Search
  second_CTA_URL: http://www.mygreenvillehome.com/buy/

sidebar_CTA:
  - CTA_image_path: /img/cta-images/001.jpg
    CTA_title: "What’s Your Greenville Home Worth?"
    CTA_text: "Are you thinking of selling your home or interested in learning about home prices in your neighborhood? We can help you."
    CTA_link_text: "Free Home Value Report"
    CTA_url: http://www.mygreenvillehome.com/sell/

second_sidebar_CTA:
  - CTA_image_path2: /img/cta-images/002.jpg
    CTA_title2: "Looking for a Greenville Home?"
    CTA_text2: "Search the entire MLS for your Greenville home."
    CTA_link_text2: "Search the MLS"
    CTA_url2: http://www.mygreenvillehome.com/buy/

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: /img/lender-headshot.jpg
  logo_path: /img/lender-logo.png
  name:
  license_number:
  company:
  company_license_number:
  phone:
  email:
  url:

socials:
  review_sm_icons: false
  facebook_url: https://www.facebook.com/Hamiltonandco
  linkedin_url: https://www.linkedin.com/in/dphamilton
  youtube_url: https://www.youtube.com/channel/UCzUdR6M5IYCfK95nnPXbLZQ
  twitter_url: https://twitter.com/dphamilton
  instagram_url:
  pinterest_url:
  zillow_url: http://www.zillow.com/profile/dhamilton/
  trulia_url: http://www.trulia.com/profile/dan-hamilton-agent-greenville-sc-84475/overview
  yelp_url: http://www.yelp.com/biz/hamilton-and-co-greenville?osq=dan+hamilton
  podcast_url:

podcast:
  title: 'Greenville Real Estate Podcast with Dan Hamilton'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the Greenville Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from Hamilton & Co. - your professional Greenville Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in Greenville, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: 'Dan Hamilton'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 40
  hero_text: Greenville Real Estate Journal presented by Hamilton & Co.
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#b40101'
  theme_color: '#999'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: black

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
